### ISSUE TITLE
Marshal load and dump error for `OpenStruct`

### ISSUE THREAD

**Issue by dsisnero** [ruby/ostruct#19]
person = OpenStruct.new
person.name = 'john smith'
person.age = 70
Marshal.load ( Marshal.dump(person))

NoMethodError: undefined method `key?' for nil:NilClass
from F:/windows/scoop/persist/ruby/gems/gems/ostruct-0.3.0/lib/ostruct.rb:226:in `new_ostruct_member!'

**Comment by marcandre** [comment]
That's embarassing, thanks for the report. I'll look at this first thing tomorrow.

**Comment by marcandre** [comment]
Fixed and released 0.3.1.
Thanks for the bug report! 👍

**Comment by claplace** [comment]
I'm absolutely ignorant in ruby, but it looks like this change made the "marshal_load" private, as an alias of a private method.

I am looking at some code doing

```
@data = OpenStruct.new

[...]

@data.marshal_load(
...
)
```

and it throws an error `private method 'marshal_load' called for #<OpenStruct> (NoMethodError)` in 3.0 (was fine in 2.7)
