### ISSUE TITLE
ERROR:  Could not find a valid gem 'ostruct' (>= 0) in any repository

### ISSUE THREAD

**Issue by Eimert** [ruby/ostruct#2]
I'm a newbie to Ruby, could you help troubleshoot the following error?
```
eimert@EIM ~ $ sudo gem install ostruct
ERROR:  Could not find a valid gem 'ostruct' (>= 0) in any repository
ERROR:  Possible alternatives: astruct, cstruct, d_struct, dstruct, hstruct```
```

Whilst I can install other gems, it seems the ostruct gem isn't found. Is it in a specific repo?

Any answer is greatly appreciated.

**Comment by hsbt** [comment]
`osctruct` gem didn't release yet. You can use ostruct without gem installation.
