### ISSUE TITLE
Release for v0.6.1 is missing

### ISSUE THREAD

**Issue by VitaliySerov** [ruby/ostruct#63]
https://github.com/ruby/ostruct/releases

Lattest in the list is v0.6.0 but according to [rubygems](https://rubygems.org/gems/ostruct/) - latest is v0.6.1

**Comment by namtx** [comment]
Pump this as our pipeline fails after upgrading gems that depend on this.

**Comment by hsbt** [comment]
https://github.com/ruby/ostruct/releases/tag/v0.6.1
